services:
  db:
    image: postgres:17
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: secret
      POSTGRES_DB: secret
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    environment:
      POSTGRES_DSN: postgresql+psycopg://secret:secret@db:5432/secret
      DB_ECHO: true
    ports:
      - "8000:8000"
    depends_on:
      - db
