# https://taskfile.dev

version: '3'

vars:
  SOURCE_FILE: src/main.py

env:
  POSTGRES_DSN: postgresql+psycopg://secret:secret@localhost:5433/secret
  DB_ECHO: true

tasks:
  default:
    cmds:
      - task --list
    silent: true

  run-dev:
    desc: Run dev server
    cmd: fastapi dev {{.SOURCE_FILE}}

  run-prod:
    desc: Run production server
    cmd: uv run granian --interface asgi {{.SOURCE_FILE}}

  check:
    desc: Run linter
    cmd: ruff check .

  format:
    desc: Format project's files
    cmd: ruff format .

  start-db:
    desc: Start docker compose file
    cmd: docker compose up -d

  stop-db:
    desc: Stop docker compose file
    cmd: docker compose down

  makemigrations:
    desc: Generate migrations
    cmd: uv run alembic revision --autogenerate -m {{.CLI_ARGS}}

  migrate:
    desc: Rollout migrations to HEAD state
    cmd: uv run alembic upgrade heads

  build:
    desc: Build docker container
    cmd: docker build -t url-shortener .