# https://taskfile.dev

version: '3'

vars:
  SOURCE_FILE: src/main.py

tasks:
  default:
    cmds:
      - task --list
    silent: true

  run-dev:
    desc: Run dev server
    cmd: fastapi dev {{.SOURCE_FILE}}

  run-prod:
    desc: Run production server
    cmd: fastapi run {{.SOURCE_FILE}}

  check:
    cmd: ruff check .

  format:
    cmd: ruff format .